core/urls.py
from django.urls import path
from .views import IndexPageView
from django.contrib.auth.decorators import login_required

core_patterns = ([
    path('', login_required(IndexPageView.as_view()), name="index"),
], 'core')

estudiante/urls.py
from .views import EstudianteCreateView, EstudianteDelete, \
    EstudianteDetailView, EstudianteList, EstudianteUpdateView, \
    GeneroCreateView, GeneroDelete, GeneroListView, GeneroUpdateView
from django.contrib.auth.decorators import login_required
from django.urls import path



estudiante_patterns = ([
    # estudiante
    path('list/<int:esta>', login_required(EstudianteList), name='list'),
    path('create/', login_required(EstudianteCreateView), name='create'),
    path('<int:pk>/', login_required(EstudianteDetailView.as_view()), name='detail'),
    path('update/<int:pk>', login_required(EstudianteUpdateView.as_view()), name='update'),
    path('delete/<int:pk>', login_required(EstudianteDelete.as_view()), name='delete'),

], 'estudiante')

genero_patterns = ([
    # genero
    path('list/', login_required(GeneroListView.as_view()), name='list'),
    path('create/', login_required(GeneroCreateView.as_view()), name='create'),
    path('update/<int:pk>', login_required(GeneroUpdateView.as_view()), name='update'),
    path('delete/<int:pk>', login_required(GeneroDelete.as_view()), name='delete'),
], 'genero')

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from estudiante.urls import estudiante_patterns, genero_patterns
from caracterizacion.urls import caracterizacion_patterns, caracterizacion_estudiante_patterns, tipo_caracterizacion_patterns
from semestre.urls import semestre_patterns
from programa.urls import programa_patterns
from core.urls import core_patterns
from reporte.urls import reporte_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    # Paths de Auth
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    # Paths core
    path('', include(core_patterns)),
    path('estudiante/', include(estudiante_patterns)),
    path('genero/', include(genero_patterns)),
    path('caracterizacion/', include(caracterizacion_patterns)),
    path('tipo/', include(tipo_caracterizacion_patterns)),
    path('caracterizacion_estudiante/', include(caracterizacion_estudiante_patterns)),
    path('semestre/', include(semestre_patterns)),
    path('programa/', include(programa_patterns)),
    path('reporte/', include(reporte_patterns)),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

caracterizacion/models.py
from django.db import models
from estudiante.models import Estudiante
from semestre.models import Semestre
from django.contrib.auth.models import User

# Create your models here.
class Tipo(models.Model):
    nombre = models.CharField(verbose_name="Nombre", max_length = 200)
    default = models.NullBooleanField(null=True, blank=True, unique=True)
    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "Tipo de caracterización"
        verbose_name_plural = "Tipo de caracterizaciones"
        ordering = ['nombre']
        db_table = 'tipo'
    

class Caracterizacion(models.Model):
    SI_NO = (
        (1,'Sí'),
        (2,'No'),
    )
    estudiante = models.ForeignKey(Estudiante, verbose_name="Estudiante", on_delete=models.CASCADE)
    descripcion = models.TextField(verbose_name="Descripción", null=True, blank=True)
    semestre = models.ForeignKey(Semestre, verbose_name="Semestre", on_delete=models.CASCADE)
    tipo = models.ForeignKey(Tipo, verbose_name="Tipo", on_delete=models.CASCADE)
    nivelado = models.IntegerField(choices = SI_NO, default=1)
    usuario = models.ForeignKey(User, verbose_name="Usuario", on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")

    def __str__(self):
        return ('{} - {}'.format(self.estudiante, self.semestre))

    class Meta:
        verbose_name = "Caracterización"
        verbose_name_plural = "Caracterizaciones"
        ordering = ['semestre']
        db_table = 'caracterizacion'

    

estudiante/models.py
from django.db import models
from programa.models import Programa
from semestre.models import Semestre
# Create your models here.

def custom_upload_to(instance, filename):
    try:
        old_instance = Estudiante.objects.get(pk=instance.pk)
        old_instance.foto.delete()
        return 'perfiles/' + filename
    except:
        return 'perfiles/' + filename


ESTADOS = (
    (0, 'Activo'),
    (1, 'Inactivo'),
    (2, 'Egresado'),
    (3, 'Graduado'),
)
TIPOS_DOCUMENTOS = (
    (0, 'Tarjeta de indentidad'),
    (1, 'Cédula'),
    (2, 'Pasaporte'),
    (3, 'Cédula extrangera'),
)

class Genero(models.Model):
    nombre = models.CharField(verbose_name="Nombre", max_length=200)

    def __str__(self):
        return self.nombre
    
    class Meta:
        db_table = 'genero'


class Estudiante(models.Model):

    nombre = models.CharField(verbose_name="Nombres", max_length=200)
    apellido = models.CharField(verbose_name="Apellidos", max_length=200)
    tipo_documento = models.IntegerField(choices=TIPOS_DOCUMENTOS, default=1)
    documento = models.CharField(verbose_name="Número de documento", max_length=200, unique=True)
    celular = models.CharField(verbose_name="Celular", max_length=200, null=True, blank=True)
    telefono = models.CharField(verbose_name="Telefono", max_length=200, null=True, blank=True)
    genero = models.ForeignKey(Genero, verbose_name="Género", on_delete=models.CASCADE)
    fecha_nacimiento = models.DateField(verbose_name="Fecha de nacimiento")
    email = models.EmailField(verbose_name="Correo electronico", null=True, blank=True, unique=True)
    direccion = models.CharField(verbose_name="Dirección", max_length=200, null=True, blank=True)
    foto = models.ImageField(upload_to=custom_upload_to, null=True, blank=True)
    programa = models.ForeignKey(Programa, on_delete=models.CASCADE)
    estado = models.IntegerField(choices=ESTADOS, default=0)
    semestre_inicio = models.ForeignKey(Semestre, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")

    def __str__(self):
        return ('{} {}'.format(self.nombre, self.apellido))

    def get_tipo_documento(self):
        tipo = TIPOS_DOCUMENTOS[self.tipo_documento][1]
        return tipo
    
    class Meta:
        db_table = 'estudiante'

estudiante/forms.py
from betterforms.multiform import MultiModelForm
from caracterizacion.models import Caracterizacion
from caracterizacion.forms import CaracterizacionBetterForm
from .models import Estudiante, Genero
from django import forms
from django.forms.widgets import SelectDateWidget


class EstudianteForm(forms.ModelForm):
    class Meta:
        model = Estudiante
        fields = ['nombre', 'apellido', 'tipo_documento', 'celular', 'telefono', 'genero', 'documento',
                  'fecha_nacimiento', 'email', 'direccion', 'foto', 'programa', 'estado']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control'}),
            'tipo_documento': forms.Select(attrs={'class': 'form-control'}),
            'celular': forms.TextInput(attrs={'class': 'form-control'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control'}),
            'genero': forms.Select(attrs={'class': 'form-control'}),
            'documento': forms.TextInput(attrs={'class': 'form-control'}),
            'fecha_nacimiento': forms.TextInput(attrs={'class': 'form-control mydatepicker date-inputmask', 'placeholder': 'Día - Mes - Año'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'direccion': forms.TextInput(attrs={'class': 'form-control'}),
            'programa': forms.Select(attrs={'class': 'form-control'}),
            'estado': forms.Select(attrs={'class': 'form-control'}),
        }

class EstudianteCrearForm(forms.ModelForm):
    class Meta:
        model = Estudiante
        fields = ['nombre', 'apellido', 'tipo_documento', 'celular', 'telefono', 'genero', 'documento',
                  'fecha_nacimiento', 'email', 'direccion', 'foto', 'programa']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control'}),
            'tipo_documento': forms.Select(attrs={'class': 'form-control'}),
            'celular': forms.TextInput(attrs={'class': 'form-control'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control'}),
            'genero': forms.Select(attrs={'class': 'form-control'}),
            'documento': forms.TextInput(attrs={'class': 'form-control'}),
            'fecha_nacimiento': forms.TextInput(attrs={'class': 'form-control date-inputmask', 'placeholder': 'Día - Mes - Año'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'direccion': forms.TextInput(attrs={'class': 'form-control'}),
            'programa': forms.Select(attrs={'class': 'form-control'}),
        }

class EstudianteEstadoForm(forms.ModelForm):
    class Meta:
        model = Estudiante
        fields = ['estado',]
        widgets = {
            'estado': forms.Select(attrs={'class': 'form-control'}),
        }


class EstudainteCaracterizacionBetterForm(MultiModelForm):
    form_classes = {
        'estudiante': EstudianteCrearForm,
        'caracterizacion': CaracterizacionBetterForm,
    }


class GeneroForm(forms.ModelForm):
    class Meta:
        model = Genero
        fields = ['nombre', ]
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
        }

estudiante/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import TemplateView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from .models import Estudiante, Genero
from braces.views import LoginRequiredMixin, SuperuserRequiredMixin
from .forms import EstudainteCaracterizacionBetterForm, EstudianteForm, GeneroForm
from caracterizacion.models import Tipo

# Create your views here.


class EstudianteDetailView(DetailView):
    model = Estudiante


def EstudianteList(request, esta):
    if esta == 0:
        estad = [0, 2]
    else:
        estad = [0, 1, 2, 3]

    estudiantes = Estudiante.objects.filter(estado__in=estad)

    contexto = {
        'estudiante_list': estudiantes,
    }
    return render(request, 'estudiante/estudiante_list.html', contexto)


def EstudianteCreateView(request):
    if request.method == 'POST':
        form = EstudainteCaracterizacionBetterForm(request.POST or None, request.FILES or None)

        if form.is_valid():
            tipo = Tipo.objects.get(default=True)
            estudiante = form['estudiante'].save(commit=False)
            caracterizacion = form['caracterizacion'].save(commit=False)
            estudiante.semestre_inicio = caracterizacion.semestre
            # import pdb; pdb.set_trace()  # Linea de test
            estudiante.save()
            caracterizacion.estudiante = estudiante
            caracterizacion.tipo = tipo
            caracterizacion.usuario = request.user
            caracterizacion.save()
            return redirect('estudiante:list', esta=0)
    else:
        pass
        form = EstudainteCaracterizacionBetterForm()
    contexto = {
        'form': form,

    }
    return render(request, 'estudiante/estudiante_form.html', contexto)

class EstudianteUpdateView(UpdateView):
    model = Estudiante
    form_class = EstudianteForm

    template_name = 'estudiante/estudiante_update_form.html'
    success_url = reverse_lazy('estudiante:list', kwargs={"esta":0})


class EstudianteDelete(DeleteView):
    model = Estudiante
    success_url = reverse_lazy('estudiante:list', kwargs={"esta":0})


class SuccessView(TemplateView):
    template_name = 'core/index.html'


class GeneroListView(LoginRequiredMixin, SuperuserRequiredMixin, ListView):
    model = Genero


class GeneroCreateView(LoginRequiredMixin, SuperuserRequiredMixin, CreateView):
    form_class = GeneroForm
    template_name = 'estudiante/genero_form.html'
    success_url = reverse_lazy('genero:list')


class GeneroDelete(LoginRequiredMixin, SuperuserRequiredMixin, DeleteView):
    model = Genero
    success_url = reverse_lazy('genero:list')


class GeneroUpdateView(LoginRequiredMixin, SuperuserRequiredMixin, UpdateView):
    model = Genero
    form_class = GeneroForm
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('genero:list')

estudiante/templates/estudiante/estudiante_confirm_delete.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <h3>Eliminar estudiante</h3>
            <button type="button" class="close" data-dismiss="modal">X</button>
        </div>
        <div class="modal-body">
            <form  role="form" action="{% url 'estudiante:delete' object.id %}" method="post">{% csrf_token %}
                <p>¿Estás seguro de que quieres eliminar el estudiante <b  class="font-weight-bold">"{{ object }}"</b>?</p>
                <p>Si elimina este estudiante tambien se eliminaran todas las caracterizaciones asosciadas a el.</p>
                <input type="submit" class="btn btn-danger btn-block" value="Sí, Borrar" />
            </form>
        </div>
        <div class="modal-footer">
            <div class="col-lg-12 text-right">
                <button type="button" class="btn btn-primary" onclick="return cerrar_modal()">
                    Cancelar
                </button>
            </div>
        </div>
    </div>
</div>

estudiante/templates/estudiante/estudiante_detail.html
{% load static%}
<div class="modal-dialog modal-lg">
  <div class="modal-content">
    <div class="modal-header">
      <h3>Detalle estudiante</h3>
      <button type="button" class="close" data-dismiss="modal">X</button>
    </div>
    <div class="modal-body">
      <div class="row">
        <!-- Column -->
        <div class="col-lg-4 col-xlg-3 col-md-5">
          <div class="card">
            <div class="card-body">
              <center>
                {% if estudiante.estado == 0 %}
                <span class="label label-success label-rouded"><h5>Activo</h5></span>
                {% elif estudiante.estado == 1 %}
                <span class="label label-danger label-rouded"><h5>Inactivo</h5></span>
                {% elif estudiante.estado == 2 %}
                <span class="label label-warning  label-rouded"><h5>Egresado</h5></span>
                {% elif estudiante.estado == 3 %}
                <span class="label label-info label-rouded"><h5>Graduado</h5></span>
                {% endif %}
                <hr>
                {% if estudiante.foto %}
                <img src="{{estudiante.foto.url}}" class="img-circle" width="150" />
                {% else %}
                <img src="{% static 'core/assets/images/no-avatar.jpg' %}" class="img-circle" width="150" />
                {% endif %}
                <h4 class="card-title m-t-10">{{ estudiante.nombre }}</h4>
                <h6 class="card-subtitle">{{ estudiante.programa }}</h6>
                <h6 class="card-subtitle">Semestre inicio: {{ estudiante.semestre_inicio }}</h6>
              </center>
            </div>
          </div>
        </div>
        <!-- Column -->
        <!-- Column -->
        <div class="col-lg-8 col-xlg-9 col-md-7">
          <div class="card">
            <!-- Nav tabs -->
            <ul class="nav nav-tabs profile-tab" role="tablist">
              <li class="nav-item"> <a class="nav-link active show" data-toggle="tab" href="#profile" role="tab">Perfil</a>
              </li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
              <!--second tab-->
              <div class="tab-pane active" id="profile" role="tabpanel">
                <div class="card-body">
                  <div class="row">
                    <div class="col-md-4 col-xs-6 b-r"> <strong>Nombre completo</strong>
                      <br>
                      <p class="text-muted">{{ estudiante.nombre }} {{ estudiante.apellido }}</p>
                    </div>
                    <div class="col-md-3 col-xs-6 b-r"> <strong>{{ estudiante.get_tipo_documento }}</strong>
                      <br>
                      <p class="text-muted">{{ estudiante.documento }}</p>
                    </div>
                    <div class="col-md-3 col-xs-6 b-r"> <strong>Fecha de nacimineto</strong>
                      <br>
                      <p class="text-muted">{{ estudiante.fecha_nacimiento }} - XX años</p>
                    </div>
                    <div class="col-md-3 col-xs-6 b-r"> <strong>Celular</strong>
                      <br>
                      <p class="text-muted">{{ estudiante.celular }}</p>
                    </div>
                    <div class="col-md-3 col-xs-6 b-r"> <strong>Telefono</strong>
                      <br>
                      <p class="text-muted">{{ estudiante.telefono }}</p>
                    </div>
                    <div class="col-md-4 col-xs-6 b-r"> <strong>Email</strong>
                      <br>
                      <p class="text-muted"><a href="mailto:{{ estudiante.email }}">{{ estudiante.email }}</a></p>
                    </div>
                    <div class="col-md-4 col-xs-6"> <strong>Dirección</strong>
                      <br>
                      <p class="text-muted">{{ estudiante.direccion }}</p>
                    </div>
                  </div>
                  <hr>
                  <a href="{% url 'caracterizacion_estudiante:list' estudiante.id %}" class="btn btn-block btn-success">
                      Ver {{estudiante.caracterizacion_set.count}} caracterizaciones</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Column -->
      </div>
    </div>
    <div class="modal-footer">
      <div class="col-lg-12 text-right">
        <a href="{% url 'estudiante:update' estudiante.id %}" class="btn btn-info">Editar</a>
        <button type="button" class="btn btn-primary" onclick="return cerrar_modal()">
          Aceptar
        </button>
      </div>
    </div>
  </div>
</div>

estudiante/templates/estudiante/estudiante_list.html
{% extends 'core/base.html' %}
{% block title %}Lista de estudiantes{% endblock %}

{% block titlulo_pagina %}Lista de estudiantes {% endblock %}
{% load static %}
{% block css %}
<link href="{% static 'core/assets/node_modules/datatables/media/css/dataTables.bootstrap4.css' %}" rel="stylesheet">
<link href="{% static 'core/assets/node_modules/bootstrap-datepicker/bootstrap-datepicker.min.css' %}" rel="stylesheet"
    type="text/css" />
{% endblock %}
{% block atras %}

<div class="btn-group">

    <a href="{% url 'estudiante:list' 1 %}" class="btn btn-warning" ><i class="fa fa-eye"></i> Ver todos</a> 
</div>

<div class="btn-group">

    <a href="{% url 'estudiante:create' %}" class="btn btn-info" style="margin: 10px"><i class="fa fa-plus-circle"></i> Crear estudiante</a> 
</div>

<div class="btn-group">

    <a href="{% url 'caracterizacion:masivo' %}" class="btn btn-success"><i class="fa fa-plus-circle"></i> Crear caracterizacion Masiva</a>
</div>
{% endblock atras %}
{% block content %}

<div class="card">
    <div class="card-body">

        <div class="table-responsive ">

            <table id="myTable" class="table table-bordered table-striped table-hover">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Documento</th>
                        <th>Programa</th>
                        <th>Estado</th>
                        <th>Semestre de inicio</th>
                        <th>Caracterizaciones</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for estudiante in estudiante_list %}
                    <tr>
                        <td>
                            <b>{{estudiante.nombre}} {{estudiante.apellido}}</b>
                        </td>
                        <td>{{estudiante.documento}}</td>
                        <td><b>{{estudiante.programa}}</b></td>
                        <td>
                            {% if estudiante.estado == 0 %}
                            <span class="label label-success label-rouded">Activo</span>
                            {% elif estudiante.estado == 1 %}
                            <span class="label label-danger label-rouded">Inactivo</span>
                            {% elif estudiante.estado == 2 %}
                            <span class="label label-warning  label-rouded">Egresado</span>
                            {% elif estudiante.estado == 3 %}
                            <span class="label label-info label-rouded">Graduado</span>
                            {% endif %}

                        </td>
                        <td>{{estudiante.semestre_inicio}}</td>
                        <td><a href="{% url 'caracterizacion_estudiante:list' estudiante.id %}" class="btn btn-block btn-success">
                                {{estudiante.caracterizacion_set.count}}</a>
                        </td>
                        <td class="text-center">
                            <div class="row">
                                <a onclick="return abrir_modal('{% url 'estudiante:detail' estudiante.id  %}')" class="btn">
                                    <span class="icon-eye font-weight-bold" data-toggle="tooltip" data-original-title="Ver"></span>
                                </a> <a style="color:rgb(2, 167, 196)" href="{% url 'estudiante:update' estudiante.id  %}"
                                    class="btn">
                                    <span class="icon-pencil font-weight-bold" data-toggle="tooltip"
                                        data-original-title="Editar"></span>
                                </a>
                                </a> <a style="color:crimson" onclick="return abrir_modal('{% url 'estudiante:delete' estudiante.id  %}')"
                                    class="btn">
                                    <span class="icon-close font-weight-bold" data-toggle="tooltip" data-original-title="Eliminar"></span>
                                </a>
                            </div>

                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<div id="popup" class="modal fade" role="dialog"></div>
{% endblock %}

{% block scripts %}
<script>
    $(function () {
        $('#myTable').DataTable();
    });
    //    $('#example23').DataTable({
    //        dom: 'Bfrtip',
    //        buttons: [
    //            'copy', 'csv', 'excel', 'pdf', 'print'
    //       ]
    //   });
    $('.buttons-copy, .buttons-csv, .buttons-print, .buttons-pdf, .buttons-excel').addClass('btn btn-primary mr-1');
</script>
<script src="{% static 'core/assets/node_modules/datatables/datatables.min.js' %}"></script>
<script>
    function abrir_modal(url) {
        $('#popup').load(url, function () {
            $(this).modal('show');
        });
        return false;
    }

    function cerrar_modal() {
        $('#popup').modal('hide');
        return false;
    }

    $(document).ready(function () {
        var table = $('#tabla').dataTable({
            "language": {
                url: "/static/localizacion/es_ES.json"
            }
        });
    });
</script>
<script src="{% static 'core/assets/node_modules/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script>
{% endblock %}

estudiante/templates/estudiante/genero_confirm_delete.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <h3>Eliminar semestre</h3>
            <button type="button" class="close" data-dismiss="modal">X</button>
        </div>
        <div class="modal-body">
            <form  role="form" action="{% url 'genero:delete' object.id %}" method="post">{% csrf_token %}
                <p>¿Estás seguro de que quieres eliminar el genero <b  class="font-weight-bold">"{{ object }}"</b>?</p>
                <p>Si elimina este genero tambien se eliminaran todos los estudiantes asociados a este genero.</p>
                <input type="submit" class="btn btn-danger btn-block" value="Sí, Borrar" />
            </form>
        </div>
        <div class="modal-footer">
            <div class="col-lg-12 text-right">
                <button type="button" class="btn btn-primary" onclick="return cerrar_modal()">
                    Cancelar
                </button>
            </div>
        </div>
    </div>
</div>

estudiante/templates/estudiante/genero_form.html
{% extends 'core/base.html' %}
{% block title %}Crear género{% endblock %}
{% block titlulo_pagina %}Crear género{% endblock %}
{% load static %}
{% block atras %}
<a href="{% url 'genero:list' %}" class="btn btn-info"> <span class="icon-arrow-left"></span>Atrás</a>

{% endblock atras %}
{% block content %}
<form role="form" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="col-md-12">
    <div class="panel panel-info">
      <div class="panel-wrapper collapse in" aria-expanded="true">
        <div class="panel-body">
          <div class="col-md-12">
            <div class="card border-dark">
              <div class="card-body">
                <!-- nombre y apellido -->
                <div class="row">
                  <div class="col-md-12">
                    <div class="form-group">
                      <label class="control-label">Nombre</label>
                      {{ form.nombre }}
                      <span class="error" style="color:red;">{{ form.nombre.errors }}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- FIN Cuerpo del modal -->
  <div class="modal-footer">
    <div class="col-lg-12 text-right">
      <button type="submit" class="btn btn-success"> <i class="fa fa-check "></i> Guardar</button>
      <a class="btn btn-danger" href="{% url 'semestre:list' %}">Cancelar</a>
    </div>
  </div>
</form>
{% endblock %}

estudiante/templates/estudiante/genero_list.html
{% extends 'core/base.html' %}
{% block title %}Lista de géneros{% endblock %}

{% block titlulo_pagina %}Lista de géneros {% endblock %}
{% load static %}
{% block css %}
<link href="{% static 'core/assets/node_modules/datatables/media/css/dataTables.bootstrap4.css' %}" rel="stylesheet">
{% endblock %}
{% block atras %}
    <a href="{% url 'genero:create' %}"  class="btn btn-info d-lg-block m-l-15"><i class="fa fa-plus-circle"></i> Crear género</a>
{% endblock atras %}
{% block content %}

<div class="card">
    <div class="card-body">

        <div class="table-responsive ">

            <table id="myTable" class="table table-bordered table-striped table-hover">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nombre</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for obj in genero_list %}
                    <tr>
                        <td>
                            <b>{{obj.id}}</b>
                        </td>
                        <td>
                            <b>{{obj.nombre}}</b>
                        </td>
                        <td class="text-center" WIDTH="50">
                            <div class="row">
                                <a style="color:royalblue" href="{% url 'genero:update' obj.id %}" class="btn">
                                    <span class="icon-pencil font-weight-bold" data-toggle="tooltip" data-original-title="Editar"></span>
                                </a>
                                <a style="color:crimson" onclick="return abrir_modal('{% url 'genero:delete' obj.id  %}')"
                                    class="btn">
                                    <span class="icon-close font-weight-bold" data-toggle="tooltip" data-original-title="Eliminar"></span>
                                </a>
                            </div>

                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<div id="popup" class="modal fade" role="dialog">

</div>

{% endblock %}
{% block scripts %}
<script>
    $(function () {
        $('#myTable').DataTable();
        $(function () {
            var table = $('#example').DataTable({
                "columnDefs": [{
                    "visible": false,
                    "targets": 2
                }],
                "order": [
                    [2, 'asc']
                ],
                "displayLength": 25,
            });
            // Order by the grouping
            $('#example tbody').on('click', 'tr.group', function () {
                var currentOrder = table.order()[0];
                if (currentOrder[0] === 2 && currentOrder[1] === 'asc') {
                    table.order([2, 'desc']).draw();
                } else {
                    table.order([2, 'asc']).draw();
                }
            });
        });
    });
    //    $('#example23').DataTable({
    //        dom: 'Bfrtip',
    //        buttons: [
    //            'copy', 'csv', 'excel', 'pdf', 'print'
    //       ]
    //   });
    $('.buttons-copy, .buttons-csv, .buttons-print, .buttons-pdf, .buttons-excel').addClass('btn btn-primary mr-1');
</script>
<script src="{% static 'core/assets/node_modules/datatables/datatables.min.js' %}"></script>
<script>
    function abrir_modal(url) {
        $('#popup').load(url, function () {
            $(this).modal('show');
        });
        return false;
    }

    function cerrar_modal() {
        $('#popup').modal('hide');
        return false;
    }

    $(document).ready(function () {
        var table = $('#tabla').dataTable({
            "language": {
                url: "/static/localizacion/es_ES.json"
            }
        });
    });
</script>
{% endblock %}